app/models.py
from app import db, login
from datetime import date
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin


class UserWordLink(db.Model):
    __tablename__ = "user_word_link"
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), primary_key=True)
    word_id = db.Column(db.Integer, db.ForeignKey("word.id"), primary_key=True)
    date = db.Column(db.DateTime, default=date.today())
    guesses = db.Column(db.Integer)

    user = db.relationship("User", back_populates="words")
    word = db.relationship("Word", back_populates="users")


class User(UserMixin, db.Model):
    __tablename__ = "user"
    id = db.Column(db.Integer, primary_key=True)
    initials = db.Column(db.String(3), index=True, unique=True)
    nickname = db.Column(db.String(64), index=True)
    password_hash = db.Column(db.String(128))
    words = db.relationship("UserWordLink", back_populates="user")

    def __repr__(self):
        return "<User {}>".format(self.nickname)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)


class Word(db.Model):
    __tablename__ = "word"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), index=True, unique=True)
    users = db.relationship("UserWordLink", back_populates="word")
    word_log = db.relationship("WordLog", backref="word", lazy="dynamic")

    def __repr__(self):
        return "<Word {}>".format(self.name)


class WordLog(db.Model):
    __tablename__ = "word_log"
    id = db.Column(db.Integer, primary_key=True)
    word_id = db.Column(db.Integer, db.ForeignKey("word.id"), nullable=True)
    date = db.Column(db.DateTime, default=date.today())

    def __repr__(self):
        return "<Word {} on date {}>".format(self.word, self.date)


@login.user_loader
def load_user(id):
    return User.query.get(int(id))

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_cors import CORS
from flask_login import LoginManager
from config import Config
from whitenoise import WhiteNoise

db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()
login.login_view = "auth.login"
login.login_message = "Please log in to access this page."


def create_app(config_class=Config):
    app = Flask(__name__, static_url_path="")
    app.config.from_object(config_class)
    CORS(app)

    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)

    from app.main import bp as main_bp

    app.register_blueprint(main_bp)

    from app.api import bp as api_bp

    app.register_blueprint(api_bp)

    from app.auth import bp as auth_bp

    app.register_blueprint(auth_bp)
    app.wsgi_app = WhiteNoise(app.wsgi_app, root="")

    return app


from app import models

app/api/__init__.py
from flask import Blueprint

bp = Blueprint("api", __name__)

from app.api import leaderboard

app/main/__init__.py
from flask import Blueprint

bp = Blueprint("main", __name__)

from app.main import routes

app/main/routes.py
from app.models import User, Word, UserWordLink, WordLog
from app.main import bp
from app import db
from flask import render_template, jsonify, request
from flask_login import login_required, current_user
from datetime import date, timedelta
from app.main.words import get_new_word
import app.main.fullwordlist as fullwordlist
import numpy as np


@bp.route("/")
@bp.route("/index")
@login_required
def index():
    return render_template("index.html")


def check_word_completed_today(word):
    today = date.today()
    user = User.query.filter_by(id=current_user.id).first()
    word = Word.query.filter_by(name=word).first()
    user_word = UserWordLink.query.filter(
        UserWordLink.user_id == user.id,
        UserWordLink.word_id == word.id,
        UserWordLink.date >= today,
    ).first()
    if user_word:
        return True

    return False


@bp.route("/get_word", methods=["GET", "POST"])
@login_required
def get_word():

    # check if there is a stored word in the word log today
    today = date.today()
    todays_word_log = WordLog.query.join(Word).filter(WordLog.date >= today).first()

    if todays_word_log:
        word = todays_word_log.word.name
        is_word_completed_today = check_word_completed_today(word)
        if is_word_completed_today:
            word = None

    # else get new word
    else:
        is_new_word = False

        # while loop to avoid duplicates
        while not is_new_word:
            word = get_new_word()
            word = Word(name=word)
            word_query = Word.query.filter_by(name=word.name).first()

            # if unique word
            if not word_query:
                is_new_word = True
                word_log = WordLog(word=word)
                db.session.add(word)
                db.session.add(word_log)
                db.session.commit()

        word = word.name

    return jsonify({"data": word})


@bp.route("/is_word", methods=["GET", "POST"])
@login_required
def is_word():
    req = request.get_json()
    word = req["word"].lower()
    is_word_bool = fullwordlist.is_word(word)

    return jsonify({"data": is_word_bool})


@bp.route("/leaderboard")
@login_required
def leaderboard():
    return render_template("leaderboard.html")

app/templates/base.html
<!doctype html>
<html>
    <head>
        <title>Staff Wordle</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"> 
        <link rel="icon" type="image/x-icon" href="{{url_for('static', filename='images/conical_favicon.ico')}}"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" href="{{url_for('static', filename='style.css')}}"/>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Staff Wordle</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="nav navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.index') }}">Play</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.leaderboard') }}">Leaderboard</a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if current_user.is_anonymous %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

    </head>
    <body>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul>
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}
        
        {% block content %}{% endblock %}

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
 
    </body>
</html>

app/templates/index.html
{% extends "base.html" %}

{% block content %}

    <div class="game-container">
        <div class="message-container">
            <p class="message-text"></p>
        </div>
        <div class="tile-container"></div>
        <div class="key-container"></div>
    </div>

    <script type="text/javascript" src="{{url_for('static', filename='main.js')}}"></script>

{% endblock %}

app/templates/leaderboard.html
{% extends "base.html" %}

{% block content %}

    <div id="buttons-div" class="container">
        <button class="leaderboard-button" id="today-button" onclick="load_today_chart()">Today's Results</button>
        <button class="leaderboard-button" id="week-button" onclick="load_week_chart()">Week Average</button>
        <button class="leaderboard-button" id="month-button" onclick="load_month_chart()">Month Average</button>
        <button class="leaderboard-button" id="all-time-button" onclick="load_all_time_chart()">All Time Average</button>
    </div>
    <div id="chart-title" class="container" >Click to view a leaderboard</div>
    <br>
    <div id="leaderboard" >

        <canvas id="myChart" width="500px">

        </canvas>
    </div>
    
<script type="text/javascript" src="{{url_for('static', filename='leaderboard.js')}}"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>



<style>
#chart-title{
    font-size: 16px;
    font-family: inherit;
    color:#C0FFFF;
    padding-top: 20px;
    display: flex;
    justify-content: center;
}

#leaderboard {
    height: 400px;
    display: flex;
    justify-content: center;
    padding-right: 40px
}
#buttons-div {
    display: flex;
    justify-content: center;
}
.leaderboard-button {
 padding: 1em 1em;
 width: 180px;
 border: 2px solid #C0FFFF;
 position: relative;
 overflow: hidden;
 background-color: transparent;
 text-align: center;
 text-transform: uppercase;
 font-size: 14px;
 transition: .3s;
 z-index: 1;
 font-family: inherit;
 color: #C0FFFF;
}

.leaderboard-button::before {
 content: '';
 width: 0;
 height: 300%;
 position: absolute;
 top: 50%;
 left: 50%;
 transform: translate(-50%, -50%) rotate(45deg);
 background: #C0FFFF;
 transition: .5s ease;
 display: block;
 z-index: -1;
}

.leaderboard-button:hover::before {
 width: 105%;
}

.leaderboard-button:hover {
 color: #111;
}

canvas{
    max-width: 500px;
    position: absolute;
    margin: 0 auto;
    padding-left: 0;
    padding-right: 0;
    display: block;
}

</style>

{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="container" style= "display: flex; flex-direction: column; align-items: center">
    <h1>Sign In</h1>
    <p>New User? <a href="{{ url_for('auth.register') }}">Click to Register!</a></p>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.initials.label }}<br>
            {{ form.initials(size=32) }}<br>
            {% for error in form.initials.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
        <p>{{ form.submit() }}</p>
    </form>
</div>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}

{% block content %}
    <div class="container" style= "display: flex; flex-direction: column; align-items: center">
        <form action="" method="post">
            {{ form.hidden_tag() }}
            <p>
                {{ form.initials.label }}<br>
                {{ form.initials(size=32) }}<br>
                {% for error in form.initials.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p>
                {{ form.nickname.label }}<br>
                {{ form.nickname(size=32) }}<br>
                {% for error in form.nickname.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p>
                {{ form.password.label }}<br>
                {{ form.password(size=32) }}<br>
                {% for error in form.password.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p>
                {{ form.password2.label }}<br>
                {{ form.password2(size=32) }}<br>
                {% for error in form.password2.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p>{{ form.submit() }}</p>
        </form>
    </div>

{% endblock %}